# Generated by Django 3.0.6 on 2020-10-14 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('add_state', models.CharField(max_length=100)),
                ('add_district', models.CharField(max_length=100)),
                ('add_town', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^+?1?\\d{9,15}$')])),
                ('photo', models.ImageField(upload_to='media/users')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/products')),
                ('details', models.TextField()),
                ('price', models.TextField(max_length=6)),
                ('published_date', models.DateField()),
                ('category', models.TextField(max_length=50)),
                ('featured', models.BooleanField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
            ],
        ),
    ]
