# Generated by Django 3.0.6 on 2020-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_ward',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
