# Generated by Django 3.0.4 on 2020-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201015_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FC', 'fiction'), ('ER', 'Engineering'), ('SC', 'Science'), ('MG', 'Managemetn'), ('LT', 'Literature'), ('AR', 'Arts'), ('SC', 'School Level'), ('RG', 'Religion'), ('LA', 'Law'), ('ET', 'Entrance Preparation'), ('GR', 'Government Jobs'), ('MI', 'Miscelleneous')], default='MI', max_length=100),
        ),
    ]
